// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR7IugrP3eqs7w1EsXxiEQQhlbL42hC2c',
    appId: '1:533135524914:web:6ac2a2901fc4057263e82b',
    messagingSenderId: '533135524914',
    projectId: 'the-food-runner-61132',
    authDomain: 'the-food-runner-61132.firebaseapp.com',
    storageBucket: 'the-food-runner-61132.firebasestorage.app',
    measurementId: 'G-P84YEW3QLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEc5c0fZrttM-inuFR6LzrfPNPULnpASE',
    appId: '1:533135524914:android:55639218874ce34363e82b',
    messagingSenderId: '533135524914',
    projectId: 'the-food-runner-61132',
    storageBucket: 'the-food-runner-61132.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGzJUL3PzrlYiG1gdIIdthD9rV7wq7ZGw',
    appId: '1:533135524914:ios:f282b4de21f1532763e82b',
    messagingSenderId: '533135524914',
    projectId: 'the-food-runner-61132',
    storageBucket: 'the-food-runner-61132.firebasestorage.app',
    iosBundleId: 'com.example.theFoodRunner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGzJUL3PzrlYiG1gdIIdthD9rV7wq7ZGw',
    appId: '1:533135524914:ios:f282b4de21f1532763e82b',
    messagingSenderId: '533135524914',
    projectId: 'the-food-runner-61132',
    storageBucket: 'the-food-runner-61132.firebasestorage.app',
    iosBundleId: 'com.example.theFoodRunner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR7IugrP3eqs7w1EsXxiEQQhlbL42hC2c',
    appId: '1:533135524914:web:baa1a706e798510263e82b',
    messagingSenderId: '533135524914',
    projectId: 'the-food-runner-61132',
    authDomain: 'the-food-runner-61132.firebaseapp.com',
    storageBucket: 'the-food-runner-61132.firebasestorage.app',
    measurementId: 'G-B5GGVBMNKV',
  );
}
